### ISSUE TITLE
Any luck with the Ombudsman?

### ISSUE THREAD

**Issue by duncan-bayne** [perryn/metroclaim#1]
Did you ever get anywhere with convincing / forcing Metro to accept forms filled out with metroclaim?

**Comment by duncan-bayne** [comment]
_bump_

**Comment by perryn** [comment]
No. Since I wasn't actually eligible to make a claim myself, I wasn't in a position to progress a complaint. I asked if any of my users wanted to take it up, but no one did ( understandably they were probably sick of the whole thing by then)

**Comment by duncan-bayne** [comment]
Right.  Well, I live on the Upwey line, and that is pretty much stuffed for half of the year.  If I ever find myself in a position where I'm eligible to make a claim, I'll use your system & complain to the ombudsman.

**Comment by duncan-bayne** [comment]
Wow this is an old issue.  Is metroclaim still a thing?  I'm now in Belgrave, and (sadly) sometimes find myself eligible for compensation.

**Comment by perryn** [comment]
No its not a thing, but I did hear that Metro now have an online claim system
